alarm:
	cd ~/InfrSW/pintos/src/threads && make

run:
	cd ~/InfrSW/pintos/src/threads && make check TESTS="tests/threads/alarm-single tests/threads/alarm-multiple tests/threads/alarm-simultaneous tests/threads/alarm-priority tests/threads/alarm-zero tests/threads/alarm-negative"

clean:
	cd ~/InfrSW/pintos/src/threads && make clean

.PHONY: alarm run clean
